### ISSUE TITLE
[OTHER] Thick style of ReplaceGuide/VSCode/style.css

### ISSUE THREAD

**Issue by hqc8848** [Aikoyori/ProgrammingVTuberLogos#208]
## Describe your issues here

I think add six characters in a CSS is very easy, just copy it and press the key for six times, and rename it, that's it.

Just like this:

```css
.editor-group-watermark {
  max-width: 500px !important;
  padding-left: 1em;
  padding-right: 1em;
}

.editor-group-watermark .letterpress {
  background-image: url("https://raw.githubusercontent.com/Aikoyori/ProgrammingVTuberLogos/main/VSCode/VSCode-Thick.png") !important;
  aspect-ratio: 8/5 !important;
}
```

And rename it like `style-Thick.css`, then upload, done.
